### ISSUE TITLE
I would like to contribute to the project. you wish to continue?

### ISSUE THREAD

**Issue by Edumatsu** [mgp25/libsignal-php#7]
I would like to contribute to the project. you wish to continue?

**Comment by CODeRUS** [comment]
what you mean? it's under development.

**Comment by Edumatsu** [comment]
I'm a php developer. I want to contribute to the project, but first wanted to know if it will continue.

**Comment by mgp25** [comment]
@Edumatsu its under development, if you want to contribute, you can send pull requests, we will review the code and merge if everything its fine

Regards

**Comment by Edumatsu** [comment]
Thank U. i'm start working soon.
